#if !defined(NODE)
#    define NODE(str, cls)
#    error "NODE() macro is not defined"
#endif

NODE("Module", Module)
NODE("ClassDef", ClassDef)
NODE("TypeDef", TypeDef)
NODE("VarDefList", VarDefList)
NODE("VarDef", VarDef)
NODE("FunDef", FunDef)
NODE("Param", Param)
NODE("ParamList", ParamList)
NODE("Stmt", Stmt)
NODE("Block", Block)
NODE("Expr", Expr)
NODE("FunCall", FunCall)
NODE("ArrayAccess", ArrayAccess)
NODE("MemberAccess", MemberAccess)
NODE("TypeIdent", TypeIdent)
NODE("TypeSpec", TypeSpec)
NODE("TypeName", TypeName)
NODE("TypeOpExpr", TypeOpExpr)
NODE("Ident", Ident)
NODE("ParenExpr", ParenExpr)
NODE("BinaryOp", BinaryOp)
NODE("UnaryOp", UnaryOp)
NODE("Cast", Cast)
NODE("BoolLit", BoolLit)
NODE("NumLit", NumLit)
NODE("StrLit", StrLit)
